### PR TITLE
Fix an issue causing bluebird warning.

### PR DESCRIPTION
**Pull request by topikachu**
Bluebird gives "Warning: a promise was created in a handler but was not returned from it" when using express-sequelize-session.
Fix this one by explicitly return null in the handler.

### CODE REVIEW

**Comment by topikachu** [comment]
The ci failed caused by installing sqlite with io.js.
What's wrong?

**Comment by dgf** [comment]
Where did you get this warning?

**Comment by topikachu** [comment]
Hi, I get this warning when put/get session data.

**Comment by nstuyvesant** [comment]
See [Issue 8](https://github.com/dgf/express-sequelize-session/issues/8) for more details.

**Comment by nstuyvesant** [comment]
See [Issue 8](https://github.com/dgf/express-sequelize-session/issues/8) for more details.

**Pull request closed without merging**
